# Permalinks
permalink: /:title

# Setup
title: Jess Ruiz
tagline: I’m a creative producer with a strong editorial background, having previous experience as a fashion writer and stylist.
url:              
paginate: 40
baseurl: http://jessruiz.london/
